ci: Adding debuging information

diff --git a/.github/actions/build/docker-setup/action.yml b/.github/actions/build/docker-setup/action.yml
--- a/.github/actions/build/docker-setup/action.yml
+++ b/.github/actions/build/docker-setup/action.yml
@@ -24,23 +24,29 @@ runs:
     - id: select-app-artifact
       shell: bash
       run: |
+        tree -a "${{ inputs.docker-path }}/"
+        $ARTIFACT" "ARTIFACT_TARGET_PATH"
         if [ -d "${{ inputs.docker-path }}/app-artifact-release" ]; then
           ARTIFACT_DIR="${{ inputs.docker-path }}/app-artifact-release"
         elif  [ -d "${{ inputs.docker-path }}/app-artifact-build" ]; then
           ARTIFACT_DIR="${{ inputs.docker-path }}/app-artifact-build"
+        else
+          echo "Unable to find artifact!"
+          exit 1
         fi
 
+
         ARTIFACT="$ARTIFACT_DIR/npm-pack.tgz"
+        echo "Found artifact $ARTIFACT"
 
         if [ ! -f "$ARTIFACT" ]; then
+          echo "Artifact is not file!"
           exit 1
         fi
 
         ARTIFACT_TARGET_PATH="${{ inputs.docker-path }}/rootfs/opt/"
         mkdir -p "$ARTIFACT_TARGET_PATH"
 
+        echo "Moving $ARTIFACT to ARTIFACT_TARGET_PATH"
         mv "$ARTIFACT" "ARTIFACT_TARGET_PATH"
-    - id: debug
-      shell: bash
-      run: |
         tree -a "${{ inputs.docker-path }}/"
